spring:
  application:
    name: zipsa
#  profiles:
#    active: privacy
#  config:
#    import: classpath:zipsa-secrets/application-privacy.yml
  datasource:
    url: jdbc:mariadb://svc.sel4.cloudtype.app:${PORT_NUMBER}/zipsa-db?characterEncoding=UTF-8&serverTimezone=UTC
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

odg:
  serviceKey: ${ODG_SERVICE_KEY}

gpt:
  key: ${GPT_KEY}

codef:
  client:
    id: ${CODEF_ID}
    secret: ${CODEF_SECERET}
    publicKey: ${CODEF_PUBLIC_KEY}
    encryptionTargetPlain: ${CODEF_ENCRYPTION_TARGET_PLAIN}


jwt:
  secret: ${JWT_SECRET}

#server:
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-type: PKCS12
#    key-store-password: ${KEYSTORE_PASSWORD}
#    enabled: true